USE ecommerce
/*
==================================================================
1. Database exploration
==================================================================
*/
-- 1.1. Check available table
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'ecommerce';	

-- 1.2.  Describe Table Structure
SELECT table_name,
       column_name,
       data_type,
       is_nullable
FROM information_schema.columns
WHERE table_schema = 'ecommerce';
/*
==================================================================
2. Summarizing Data Using Aggregations
==================================================================
*/
-- 2.1. How many years of data do we have? 
SELECT 
    COUNT(DISTINCT YEAR(order_purchase_timestamp)) AS number_of_years
FROM orders2;

--  2.2. Count the number of orders placed every year
SELECT YEAR(order_purchase_timestamp) ,COUNT(order_id) as "Number of orders placed"
FROM orders2
GROUP BY YEAR(order_purchase_timestamp) 
ORDER BY YEAR(order_purchase_timestamp);

-- 2.3. Which order has the highest total payment value?
SELECT order_id, SUM(payment_value) as total_payment
FROM payments
GROUP BY order_id
ORDER BY SUM(payment_value) DESC 
LIMIT 1;

-- 2.4. What is the total revenue generated by each product category
SELECT p.product_category, SUM(pm.payment_value) AS "total_sales"
FROM products as p
JOIN order_items as o ON p.product_id = o.product_id
JOIN payments as pm ON pm.order_id = o.order_id
GROUP BY p.product_category;

-- 2.5. Which city has the highest number of orders?
SELECT customers.customer_city, COUNT(orders2.order_id) as number_of_orders
FROM orders2 
JOIN customers ON customers.customer_id = orders2.customer_id
GROUP BY customers.customer_city
ORDER BY COUNT(orders2.order_id) DESC
LIMIT 1;
/*
==================================================================
3. Customer & Revenue Performance Analysis
==================================================================
*/
-- 3.1. Calculate the percentage of orders that were paid in installments 
SELECT 100.0*(SUM(CASE WHEN payment_installments > 1 THEN 1 ELSE 0 END)/COUNT(*)) as percentage_installment
FROM payments;
-- 3.2. Calculate the total revenue generated by each seller, and rank them by revenue.
WITH revenue as
( 
SELECT s.seller_id, SUM(p.payment_value) as sum_payment_value
FROM payments p
JOIN orders2 o
ON p.order_id = o.order_id
JOIN order_items od
ON o.order_id = od.order_id
JOIN sellers s
ON od.seller_id = s.seller_id
GROUP BY s.seller_id
)
SELECT seller_id, sum_payment_value, DENSE_RANK() OVER(ORDER BY sum_payment_value DESC) as ranking
FROM revenue;

-- 3.3. Calculate the cumulative sales per month for each year.
WITH total_sales as 
(SELECT YEAR(o.order_purchase_timestamp) as 'year', 
		MONTH(o.order_purchase_timestamp) as 'month', SUM(p.payment_value) as 'sales'
FROM orders2 o
JOIN payments p ON o.order_id = p.order_id
GROUP BY YEAR(o.order_purchase_timestamp), MONTH(o.order_purchase_timestamp)
ORDER BY YEAR(o.order_purchase_timestamp) )
SELECT *, SUM(sales) OVER (PARTITION BY year ORDER BY month ASC) as cumulative_sales
FROM total_sales;

-- 3.4. How are customers distributed between one-time and repeat purchasers,
--  and what is the repeat customer rate?
WITH order_count_table as 
(SELECT  c.customer_unique_id, COUNT(o.order_id) as order_count
FROM customers c
JOIN orders2 o ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id)
SELECT SUM(CASE WHEN order_count = 1 THEN 1 END) as One_time_customers,
	   SUM(CASE WHEN order_count > 1 THEN 1 END) as Repeat_customers,
	   ROUND(100.0 * SUM(CASE WHEN order_count > 1 THEN 1 END) / COUNT(*),2) as repeat_customer_rate
FROM order_count_table;
-- 3.5. What share of total revenue comes from repeat customers?
WITH repeat_customers as 
(SELECT  c.customer_unique_id, COUNT(o.order_id) as order_count
FROM customers c
JOIN orders2 o ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id
HAVING order_count > 1),
revenue as
(SELECT c.customer_unique_id, SUM(pm.payment_value) as customer_revenue
FROM payments pm
JOIN orders2 o ON o.order_id = pm.order_id
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id),
revenue_per_customer as
(SELECT r.customer_unique_id, r.customer_revenue
FROM repeat_customers rc
JOIN revenue r ON rc.customer_unique_id = r.customer_unique_id)
SELECT COUNT(customer_unique_id) as repeat_customers, 
		ROUND(SUM(customer_revenue)/ (SELECT SUM(payment_value) FROM payments)*100,2)
		as revenue_percentage
FROM revenue_per_customer;

-- 3.6.What is the customer retention rate within three months after the first purchase?
WITH the_first_order as 
(SELECT c.customer_unique_id, MIN(o.order_purchase_timestamp) as "first_order"
FROM orders2 o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_unique_id),
retained_customer as
(SELECT tf.customer_unique_id
FROM the_first_order tf
JOIN orders2 o 
ON o.order_purchase_timestamp > tf.first_order
AND o.order_purchase_timestamp <= DATE_ADD(tf.first_order, interval 3 month)
JOIN customers c
ON c.customer_unique_id = tf.customer_unique_id AND c.customer_id = o.customer_id
GROUP BY tf.customer_unique_id)
SELECT ROUND(COUNT(r.customer_unique_id) / COUNT(t.customer_unique_id)*100,2) as retention_rate
FROM the_first_order t
LEFT JOIN retained_customer r ON t.customer_unique_id = r.customer_unique_id;
